### ISSUE TITLE
Add Indian flag

### ISSUE THREAD

**Issue by kushalpandya** [dhanishgajjar/css-flags#2]
Indian flag 🇮🇳 is missing from the collection, please add it. ☺️

**Comment by dhanishgajjar** [comment]
It’s not missing it’s left out along with many other countries which were not possible with a single div at that time. Hopefully when I get time to refactor and find new ways I’ll add the missing ones

**Comment by gusbemacbe** [comment]
@dhanishgajjar, also check https://codepen.io/krish4u/pen/zrRJrL

**Comment by dhanishgajjar** [comment]
@gusbemacbe that is still not a single div flag :)
